### ISSUE TITLE
Installer slow

### ISSUE THREAD

**Issue by Alistair1231** [userdocs/lftp-windows#17]
Hi!
The installer seems to choose a cygwin mirror (cygwin.mirror.uk.sargasso.net) which is unbearably slow. I am from the netherlands, so it's not distance or anything.
Would either a choice, like in the cygwin setup or just another, faster mirror be possible to implement?

EDIT: After looking more into it, I noticed that you created a variable which I could easily change. So thanks!
```
:: change the URL to the closest mirror https://cygwin.com/mirrors.html
set CYGWIN_MIRROR=https://ftp.fau.de/cygwin/
```
But maybe for other people who blindly run the script make a disclaimer in the "installing" section?

**Comment by userdocs** [comment]
It's mentioned in the introduction but not really documented. 

> If you require a specific setting to be modified, configuration options are set in the LFTP4WIN-installer.cmd using a text editor.

The real problem is cygwin provides no way to automatically determine the fastest mirror and there is no simple way to detect it before the script is run. After cygwin is installed it's easy, but it's too late by then.

I'll improve the readme.

**Comment by userdocs** [comment]
it's done, thanks for the feedback.
